# Gradle settings
org.gradle.jvmargs=-Xmx2G -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.daemon=false

# Isolate gradle cache to project directory
systemProp.gradle.user.home=./.gradle_repo

# Point toolchain to local JDK 21
org.gradle.java.installations.paths=E:/worksmc/JETT-1.20.6/runtime/jdk-21.0.7+10

# ============ Environment Properties ============
minecraft_version=1.20.6
minecraft_version_range=[1.20.6,1.21)
forge_version=50.2.8
forge_version_range=[50,)
loader_version_range=[50,)

# Mappings: official (no extra plugins needed)
mapping_channel=official
mapping_version=1.20.6

# ============ Mod Properties ============
mod_id=jett
mod_name=Just Enough Tooltips
mod_license=MIT
mod_version=1.5.0-Forge-1.20.6
mod_group_id=com.shao.jett
mod_authors=Shao_Zhige
mod_description=Enough your tooltips.
